"""LeftyDevKit combined server — serves the 3D landing site AND the Corruption
Ledger API + tool on one port. Deployable as a single container.

    python app.py            →  http://127.0.0.1:8000  (site + /api/* + /tool)

The ledger tracker (from ~/Projects/corruption-counter) is vendored under
server/tracker/ so this repo is fully self-contained (except the data DB which
is regenerated by `python -m tracker.refresh` from server/).

Routes
  /                       the leftydevkit-3d particle site
  /assets/*               site assets (fist.png etc.)
  /api/*                  corruption ledger JSON API
  /tool                   the full ledger explorer (tracker web/)
  /healthz                liveness
"""
from __future__ import annotations
import pathlib
from flask import Flask, Response, send_from_directory, redirect
from tracker import server as ledger_mod   # vendored ledger module (has .app)

L = ledger_mod.app                            # the ledger Flask app

ROOT = pathlib.Path(__file__).resolve().parent
# The 3D site (index.html + assets) lives next to app.py in the container (/app),
# but one level up in the local repo (server/ → repo root). Detect whichever works.
if (ROOT / "index.html").is_file():
    SITE = ROOT
else:
    SITE = ROOT.parent
WEB = ROOT / "web"                          # ledger explorer (tracker web/)

app = Flask(__name__, static_folder=None)


def _cors(resp: Response) -> Response:
    resp.headers["Access-Control-Allow-Origin"] = "*"
    resp.headers["Cache-Control"] = "public, max-age=60"
    return resp


app.after_request(_cors)


# ── The 3D landing site (root) ──
@app.get("/")
def site():
    return send_from_directory(SITE, "index.html")


@app.get("/assets/<path:p>")
def site_assets(p):
    return send_from_directory(SITE / "assets", p)


@app.get("/favicon.ico")
def favicon():
    return redirect("/assets/fist.png")


# ── Register the ledger app's API + explorer routes onto this app ──
# Skip its "/" (that's our 3D site) and its "/<path:p>" catch-all (ours too).
LEDGER_SKIP = {"/", "/<path:p>", "/favicon.ico"}

for rule in list(L.url_map.iter_rules()):
    r = rule.rule
    if r in LEDGER_SKIP:
        continue
    view = L.view_functions[rule.endpoint]
    endpoint = f"ledger_{rule.endpoint}"
    methods = sorted((rule.methods or {"GET"}) - {"HEAD", "OPTIONS"}) or ["GET"]
    app.add_url_rule(r, endpoint, view, methods=methods)


# ── Everything else → site files (e.g. /tool fallback, /data/*) ──
@app.get("/<path:p>")
def site_other(p):
    f = SITE / p
    if f.is_file():
        return send_from_directory(SITE, p)
    return ("not found", 404)


if __name__ == "__main__":
    # Coolify routes this app to :3000 (Traefik label). Listen there.
    app.run(host="0.0.0.0", port=int(__import__("os").environ.get("PORT", 3000)), debug=False)